apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: avatares-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: avatares-staging.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 80
