apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus.yml=prometheus-config.yml
  - name: grafana-datasources
    files:
      - prometheus.yml=grafana/datasources/prometheus.yml
  - name: grafana-dashboard-provisioning
    files:
      - dashboards.yml=grafana/provisioning/dashboards/dashboards.yml
  - name: grafana-dashboard-avatars
    files:
      - avatars.json=dashboards/avatars.json
resources:
  - prometheus.yaml
  - grafana.yaml